FROM node:18.18 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18.18 as production
WORKDIR /app
COPY --from=builder /app/dist/ /app/dist/
COPY package.json .
COPY vite.config.ts .
RUN npm install typescript
EXPOSE 8080
CMD [ "npm", "run", "preview" ]
