name: Reject pending deployments

inputs:
  token:
    description: Github Access Token
    required: true
  branch:
    description: Branch
    default: ${{ github.event.pull_request.head.ref }}

runs:
  using: "composite"
  steps:
    - id: list-waiting-runs
      name: List runs with waiting status related to (${{ inputs.branch }})
      shell: bash
      run: |
        curl -L --output waiting_runs.json \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs?status=waiting&branch=${{ inputs.branch }}

    - id: show-waiting-runs
      shell: bash
      run: cat waiting_runs.json

    - id: reject-pending-deployments
      name: Reject all pending deployments
      shell: bash
      run: |
        cat waiting_runs.json | jq '.workflow_runs | .[] | select( .head_branch == "${{ inputs.branch }}" ) | .id' | while read run_id; do
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel
        done
