name: Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
    secrets:
      FIREBASE_CONFIG_BASE64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}

  e2e-chrome-tests:
    name: 'E2E Chrome Tests - Desktop'
    needs: build
    uses: ./.github/workflows/e2e-tests.yml
    with:
      isManual: false
      platform: desktop
    secrets:
      TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME_1 }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD_1 }}

  e2e-chrome-mobile-tests:
    name: 'E2E Chrome Tests - Mobile'
    needs: build
    uses: ./.github/workflows/e2e-tests.yml
    with:
      isManual: false
      platform: mobile
    secrets:
      TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME_2 }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD_2 }}

  deploy-preview-website:
    name: 'Deploy Production Website'
    needs: [ build, e2e-chrome-tests, e2e-chrome-mobile-tests ]
    uses: ./.github/workflows/deploy.yml
    with:
      isPreview: false
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIREBASE_SERVICE_ACCOUNT_LANGUAGES_LEARNER: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LANGUAGES_LEARNER }}
