name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Write Firebase config
        run: |
          echo ${{ secrets.FIREBASE_CONFIG }} | base64 -d > firebase.config.json
      - name: Build dependencies
        run: yarn run build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
  deploy_live_website:
    name: Deploy Prod
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
          projectId: "${{ secrets.GOOGLE_PROJECT_ID }}"
          channelId: live
