name: Pull request

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Write Firebase config
        run: |
          echo ${{ secrets.FIREBASE_CONFIG }} | base64 -d > firebase.config.json

      - run: npx cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: npm run build
      - run: npm run lint
      - run: npm run test:ci

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: dist

  e2e-chrome-tests:
    environment: manual_e2e_tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    needs: build
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1, 2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: "E2E Tests - Chrome"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          start: npm run preview
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "E2E - Chrome"
          spec: cypress/e2e/*
          config-file: cypress.config.ts
          config: "{\"e2e\":{\"baseUrl\":\"http://localhost:8080\"}}"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
          TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME_1 }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD_1 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-chrome-mobile-tests:
    environment: manual_e2e_tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    needs: build
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1, 2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: "E2E Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          start: npm run preview
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "E2E - Chrome - Mobile"
          spec: cypress/e2e/*
          config-file: cypress.config.ts
          config: "{\"e2e\":{\"baseUrl\":\"http://localhost:8080\",\"viewportWidth\":400,\"viewportHeight\":660}}"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
          TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME_2 }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD_2 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_preview_website:
    environment: deploy_preview
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
          expires: 7d
          projectId: "${{ secrets.GOOGLE_PROJECT_ID }}"

  delete_preview_website:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: w9jds/firebase-action@v12.4.0
        with:
          # https://github.com/FirebaseExtended/action-hosting-deploy/issues/60
          args: hosting:channel:list | awk -v pr_number="pr${{ github.event.pull_request.number }}" '$0 ~ pr_number { print $2 }' | xargs -I {} firebase hosting:channel:delete {} --force
        env:
          GCP_SA_KEY: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
          PROJECT_ID: "${{ secrets.GOOGLE_PROJECT_ID }}"
